name: stats
channels:
  - conda-forge
dependencies:
  - cython=0.29.23
  - ephem=3.7.7.1
  - fbprophet=0.7.1
  -pip:
    - streamlit==0.80.0
    - plotly==4.14.3
    - yfinance==0.1.59
    - yahoo-fin==0.8.8
    - datetime==4.3
    - yahoo_finance
